### ISSUE TITLE
readme doesn't mention grunt-cli

### ISSUE THREAD

**Issue by mgrider** [dariusk/grunt-init-twitter-bot#1]
Following the readme was pretty straight forward, but as a complete node newb, I didn't have grunt installed at all. Obviously (in hindsight) that was as easy as `sudo npm install -g grunt-cli`, but it took some googling to figure out. I think it should get mentioned in the readme!

Thanks for making this!

**Comment by dariusk** [comment]
Totally missed this notification. Fixed!
